### ISSUE TITLE
Multiple biomes per island

### ISSUE THREAD

**Issue by tastybento** [BentoBoxWorld/addon-biomes#2]
_From @Poslovitch on March 29, 2017 18:29_

_From @Poslovitch on February 10, 2017 5:57_

Allow player to have multiple biomes on their island : /is biome [biome] [radius].
Useful to set precisely where slimes should spawn and others...

_Copied from original issue: tastybento/askyblock#504_

_Copied from original issue: tastybento/ASkyBlock-Bugs-N-Features#24_

**Comment by BONNe** [comment]
Users (and also admins) can change biomes in 3 ways:
- on whole island
- by chunk 
- by specified range

In Alpha 1 users can do it with GUI. In Alpha 2 users can change biome via `/biomes set <biome> [<type>] [<range>]` command.
